SARVAM_STT_TRANSLATE_URL = "https://api.sarvam.ai/speech-to-text-translate"
SARVAM_PIECE_SECONDS = 25
AUDIO_CHUNK_MINUTES = 10
MAX_WORKERS = 4
MAX_RETRIES = 3
REQUEST_TIMEOUT = 120

SUMMARIZE_CHUNK_SIZE = 3000
SUMMARIZE_CHUNK_OVERLAP = 200
VECTOR_CHUNK_SIZE = 900
VECTOR_CHUNK_OVERLAP = 150
RETRIEVER_K = 6
RETRIEVER_FETCH_K = 20

DOWNLOAD_DIR = "downloads"
CHROMA_DIR = "vector_db"
CHROMA_COLLECTION_NAME = "meeting_transcript"
EMBEDDING_MODEL = "all-MiniLM-L6-v2"
